# Generated by Django 3.1.7 on 2021-06-13 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Sprint',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('project', models.CharField(max_length=1024)),
                ('issue_type', models.CharField(max_length=1024)),
                ('summary', models.CharField(max_length=2048)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='None', max_length=16)),
                ('priority', models.CharField(default='None', max_length=16)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jira.sprint')),
                ('sub_task', models.ManyToManyField(blank=True, related_name='sub_tasks', to='jira.Ticket')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticketimages/')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.ticket')),
            ],
            options={
                'verbose_name_plural': 'TicketImage',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('edited', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.ticket')),
                ('ticket_comment_dislikes', models.ManyToManyField(related_name='ticket_comment_dislikes', to=settings.AUTH_USER_MODEL)),
                ('ticket_comment_likes', models.ManyToManyField(related_name='ticket_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TicketComment',
            },
        ),
    ]
