# Generated by Django 3.1.7 on 2021-06-13 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Improvement', 'Improvement'), ('Story', 'Story'), ('Test', 'Test'), ('Epic', 'Epic')], default='Bug', max_length=1024),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('None', 'None')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.CharField(choices=[('Bookrec', 'Bookrec'), ('Jira', 'Jira'), ('Dashboard', 'Dashboard')], default='Bookrec', max_length=1024),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
